apiVersion: ar.dev/v1alpha1
kind: Deployment
metadata:
  name: k8shelperanthropic-kagent
spec:
  targetRef:
    kind: Agent
    name: k8shelperanthropic
    tag: "1.0.0"
  runtimeRef:
    kind: Runtime
    name: kagent
  env:
    MODEL_PROVIDER: anthropic
    MODEL_NAME: claude-sonnet-4-6
