apiVersion: ar.dev/v1alpha1
kind: Deployment
metadata:
  name: demochatbot
spec:
  providerRef:
    kind: Provider
    name: AWS
  targetRef:
    kind: Agent
    name: demochatbot
    version: "1.0.4"
