apiVersion: ar.dev/v1alpha1
kind: Deployment
metadata:
  name: k8shelper-kagent
spec:
  targetRef:
    kind: Agent
    name: k8shelper
    tag: "1.0.0"
  runtimeRef:
    kind: Runtime
    name: kagent
  deploymentRefs:
    - name: github-copilot-mcp-kagent
  env:
    MODEL_PROVIDER: gemini
    MODEL_NAME: gemini-3.5-flash
